- name: Install Ubuntu-only core packages
  package: name={{ item }}
  when: is_ubuntu
  with_items:
    - build-essential
    - openssh-server
    - smbclient
    - xsel

- name: Install ubuntu-restricted-extras
  package: name=ubuntu-restricted-extras
  when: is_ubuntu
  ignore_errors: True # case multiverse repo is not enabled

- name: Install OSX-only core packages
  package: name={{ item }}
  when: is_osx
  with_items:
    - coreutils
    - findutils
    - gawk
    - gnu-getopt
    - gnu-indent
    - gnu-sed
    - gnu-tar
    - gnutls
    - grc
    - gpg
    - unrar
    - watch

- name: Install core packages
  package: name={{ item }}
  with_items:
    - curl
    - git
    - htop
    - vim
    - wget
    - zsh
    - ncdu
    - tree

- name: Gets the zsh path
  shell: which zsh
  register: bin_zsh

- name: Add homebrew zsh to /etc/shells
  lineinfile: dest=/etc/shells line='{{ bin_zsh.stdout }}'
  become: True
