---
- name: Add node apt keys
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  when: is_ubuntu
- name: Add node repositories
  apt_repository: repo='{{ item }} https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main'
  with_items:
    - deb
    - deb-src
  when: is_ubuntu

- name: Install Node
  package: name=nodejs
