# https://github.com/sindresorhus/quick-look-plugins
- name: Install QuickLook plugins
  homebrew_cask: name={{item}}
  with_items:
    - betterzipql
    - qlcolorcode
    - qlimagesize
    - qlmarkdown
    - qlprettypatch
    - qlstephen
    - quicklook-csv
    - quicklook-json
    - suspicious-package
    - webpquicklook
  when: is_osx
